spring.application.name=car-rental-service

spring.profiles.active=dev

# H2 Database
spring.datasource.url=jdbc:h2:mem:car_rental_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=none

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Thymeleaf
spring.thymeleaf.cache=false

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=ce22abcd9466aec794d60cf7ff878f515c552252bc0d117d32caadea74dd52c2fb7a4b48a4b31d6e
jwt.expiration=900000