# H2 Console enabled only in dev
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Dev cookie settings
app.security.cookie-secure=false
app.security.swagger-public=true
app.security.h2-public=true
app.security.csrf-enabled=false