spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.security.cookie-secure=false
app.security.h2-public=true
app.security.csrf-enabled=false