spring.h2.console.enabled=false
spring.jpa.show-sql=false

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

app.security.cookie-secure=true
app.security.h2-public=false
app.security.csrf-enabled=true